name: Publish Blog Posts

on:
  push:
    branches:
      - main
    paths:
      - '*.md'  # Trigger only when Markdown files are added or updated.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Markdown posts to API
        env:
          API_URL: https://idleworkshop.com/api/posts  # Replace with your actual API URL
          API_TOKEN: ${{ secrets.BLOG_API_TOKEN }} # Auth token (set this in GitHub Secrets)
        run: |
          for file in *.md; do
            TITLE=$(basename "$file" .md)
            CONTENT=$(cat "$file" | jq -Rs .)  # Read file content safely
            echo "Publishing $TITLE"

            curl -X POST "$API_URL" \
              -H "Content-Type: application/json" \
              -H "Authorization: $API_TOKEN" \
              -d '{"title": "'"$TITLE"'", "content": '"$CONTENT"'}'
          done
