name: Publish Blog Posts
on:
  push:
    branches:
      - main
    paths:
      - '*.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Send Markdown posts to API
        env:
          API_URL: https://idleworkshop.com/api/posts
          API_TOKEN: ${{ secrets.BLOG_API_TOKEN }}
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la *.md || echo "No .md files found"
          
          for file in *.md; do
            if [ -f "$file" ]; then
              TITLE=$(basename "$file" .md)
              # Format content as JSON string properly
              CONTENT=$(cat "$file" | jq -Rs .)
              
              # Debug the actual payload
              PAYLOAD=$(jq -n \
                --arg title "$TITLE" \
                --arg content "$CONTENT" \
                '{"title": $title, "content": $content}')
              
              echo "Processing file: $file"
              echo "Title: $TITLE"
              echo "Payload preview (first 100 chars):"
              echo "$PAYLOAD" | head -c 100
              
              # Send request and capture response
              RESPONSE=$(curl -X POST "$API_URL" \
                -H "Content-Type: application/json" \
                -H "Authorization: $API_TOKEN" \
                -d "$PAYLOAD" \
                -w "\nHTTP_STATUS:%{http_code}" \
                -s)
              
              HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d":" -f2)
              RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')
              
              echo "Status code: $HTTP_STATUS"
              echo "Response body: $RESPONSE_BODY"
              
              if [ "$HTTP_STATUS" != "201" ]; then
                echo "Error publishing $TITLE"
                exit 1
              fi
            fi
          done
